import Head from "next/head";
import Link from "next/link";
import Calendar from 'src/components/Calendar'
import {type NextPage } from 'next'
import { api } from "~/utils/api"

  
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name= 'description' content= 'Generated by create -t3-app' />
        <link rel = 'icon' href='/favicon.ico' />

      </Head>  


      <main>
          <Calendar/>
      </main>
    </>
  )
}

export default Home
